// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Album struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Artist struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Links       sql.NullString `json:"links"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type ArtistsAlbum struct {
	ArtistID int64 `json:"artist_id"`
	AlbumID  int64 `json:"album_id"`
}

type Playlist struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type Track struct {
	ID          int64          `json:"id"`
	Title       string         `json:"title"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type TracksAlbum struct {
	TrackID int64 `json:"track_id"`
	AlbumID int64 `json:"album_id"`
	Rank    int64 `json:"rank"`
}

type TracksArtist struct {
	TrackID  int64 `json:"track_id"`
	ArtistID int64 `json:"artist_id"`
	Rank     int64 `json:"rank"`
}

type TracksPlaylist struct {
	TrackID    int64 `json:"track_id"`
	PlaylistID int64 `json:"playlist_id"`
	Rank       int64 `json:"rank"`
}
