// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"
)

type Album struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Artist struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Links       string    `json:"links"`
	CreatedAt   time.Time `json:"created_at"`
}

type ArtistsAlbum struct {
	ArtistID int64 `json:"artist_id"`
	AlbumID  int64 `json:"album_id"`
}

type Playlist struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type Track struct {
	ID          int64     `json:"id"`
	Title       string    `json:"title"`
	Description *string   `json:"description"`
	Tags        *string   `json:"tags"`
	CreatedAt   time.Time `json:"created_at"`
}

type TracksAlbum struct {
	TrackID int64 `json:"track_id"`
	AlbumID int64 `json:"album_id"`
	Rank    int64 `json:"rank"`
}

type TracksArtist struct {
	TrackID  int64 `json:"track_id"`
	ArtistID int64 `json:"artist_id"`
	Rank     int64 `json:"rank"`
}

type TracksPlaylist struct {
	TrackID    int64 `json:"track_id"`
	PlaylistID int64 `json:"playlist_id"`
	Rank       int64 `json:"rank"`
}
