// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const getAlbumById = `-- name: GetAlbumById :one
SELECT  al.id,
        al.name,
        al.description,
        al.created_at,
        GROUP_CONCAT(ar.id, ',')     AS artist_ids,
        GROUP_CONCAT(ar.name, ',')   AS artist_names
  FROM  albums al
  LEFT  JOIN artists_albums aa  ON al.id = aa.album_id
  LEFT  JOIN artists ar         ON aa.artist_id = ar.id
 WHERE  al.id = ?
 GROUP  BY 1,2,3,4
`

type GetAlbumByIdRow struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"createdAt"`
	ArtistIds   string    `json:"artistIds"`
	ArtistNames string    `json:"artistNames"`
}

func (q *Queries) GetAlbumById(ctx context.Context, id int64) (GetAlbumByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getAlbumById, id)
	var i GetAlbumByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.ArtistIds,
		&i.ArtistNames,
	)
	return i, err
}

const getAlbumByName = `-- name: GetAlbumByName :one
SELECT  a.id
  FROM  albums a
 WHERE  a.name = ?
`

func (q *Queries) GetAlbumByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getAlbumByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getAllTrackItems = `-- name: GetAllTrackItems :many
SELECT  t.id                                       AS track_id,
        t.title,
        al.id                                      AS album_id,
        al.name                                    AS album_name,
        CAST(JSON_GROUP_ARRAY(ar.id) AS TEXT)      AS artist_ids,
        CAST(JSON_GROUP_ARRAY(ar.name) AS TEXT)    AS artist_names
  FROM  tracks AS t
  JOIN  tracks_artists AS tar         ON t.id = tar.track_id
  JOIN  artists AS ar                 ON tar.artist_id = ar.id
  LEFT  JOIN tracks_albums AS tal     ON t.id = tal.track_id
  LEFT  JOIN albums AS al             ON tal.album_id = al.id
 GROUP  BY 1,2,3,4
 ORDER  BY t.created_at
`

type GetAllTrackItemsRow struct {
	TrackID     int64   `json:"trackId"`
	Title       string  `json:"title"`
	AlbumID     *int64  `json:"albumId"`
	AlbumName   *string `json:"albumName"`
	ArtistIds   string  `json:"artistIds"`
	ArtistNames string  `json:"artistNames"`
}

func (q *Queries) GetAllTrackItems(ctx context.Context) ([]GetAllTrackItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllTrackItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllTrackItemsRow
	for rows.Next() {
		var i GetAllTrackItemsRow
		if err := rows.Scan(
			&i.TrackID,
			&i.Title,
			&i.AlbumID,
			&i.AlbumName,
			&i.ArtistIds,
			&i.ArtistNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistById = `-- name: GetArtistById :one
SELECT  a.id, a.name, a.description, a.links, a.created_at
  FROM  artists a
 WHERE  a.id = ?
`

func (q *Queries) GetArtistById(ctx context.Context, id int64) (Artist, error) {
	row := q.db.QueryRowContext(ctx, getArtistById, id)
	var i Artist
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Links,
		&i.CreatedAt,
	)
	return i, err
}

const getArtistByName = `-- name: GetArtistByName :one
SELECT  a.id
  FROM  artists AS a
 WHERE  a.name = ?
`

func (q *Queries) GetArtistByName(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getArtistByName, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTrackItemById = `-- name: GetTrackItemById :one
SELECT  t.id                                       AS track_id,
        t.title,
        al.id                                      AS album_id,
        al.name                                    AS album_name,
        CAST(JSON_GROUP_ARRAY(ar.id) AS TEXT)      AS artist_ids,
        CAST(JSON_GROUP_ARRAY(ar.name) AS TEXT)    AS artist_names
  FROM  tracks AS t
  JOIN  tracks_artists AS tar         ON t.id = tar.track_id
  JOIN  artists AS ar                 ON tar.artist_id = ar.id
  LEFT  JOIN tracks_albums AS tal     ON t.id = tal.track_id
  LEFT  JOIN albums AS al             ON tal.album_id = al.id
 WHERE  t.id = ?
 GROUP  BY 1,2,3,4
`

type GetTrackItemByIdRow struct {
	TrackID     int64   `json:"trackId"`
	Title       string  `json:"title"`
	AlbumID     *int64  `json:"albumId"`
	AlbumName   *string `json:"albumName"`
	ArtistIds   string  `json:"artistIds"`
	ArtistNames string  `json:"artistNames"`
}

func (q *Queries) GetTrackItemById(ctx context.Context, id int64) (GetTrackItemByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getTrackItemById, id)
	var i GetTrackItemByIdRow
	err := row.Scan(
		&i.TrackID,
		&i.Title,
		&i.AlbumID,
		&i.AlbumName,
		&i.ArtistIds,
		&i.ArtistNames,
	)
	return i, err
}
